### ISSUE TITLE
click function exit the app after add this library

### ISSUE THREAD

**Issue by mkansara** [leecrossley/cordova-plugin-transport-security#5]
Hi,

I working on cordova/phonegap application. when i add this library to application, app run properly on ios simulator but on real device when i on-click the or navigate the page it'll exit the app. I don't know what happen with app.

**Comment by leecrossley** [comment]
I don't think the issue is related to this plugin, I'll close this for now but can you provide a sample or at least code snippet that explains your issue I'll reopen.
