### ISSUE TITLE
Usage info

### ISSUE THREAD

**Issue by alrick** [leecrossley/cordova-plugin-transport-security#6]
Hey there!

Once the plugin is installed, the README explains you can edit `plugin.xml` to add `NSExceptionDomains`.
How is this reflected in the info.plist? Should it be updated on the next `cordova build ios` ?

**Comment by johnborges** [comment]
Same question. For me my `.plist` doesn't change after modifying the `plugin.xml` as described.

**Comment by leecrossley** [comment]
Please see #4 and updated readme
